// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.0--rc1
// source: value.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CacheItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CreatedAt     int64                  `protobuf:"varint,1,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,2,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	UpdatedCount  int64                  `protobuf:"varint,3,opt,name=updatedCount,proto3" json:"updatedCount,omitempty"`
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CacheItem) Reset() {
	*x = CacheItem{}
	mi := &file_value_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheItem) ProtoMessage() {}

func (x *CacheItem) ProtoReflect() protoreflect.Message {
	mi := &file_value_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheItem.ProtoReflect.Descriptor instead.
func (*CacheItem) Descriptor() ([]byte, []int) {
	return file_value_proto_rawDescGZIP(), []int{0}
}

func (x *CacheItem) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *CacheItem) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *CacheItem) GetUpdatedCount() int64 {
	if x != nil {
		return x.UpdatedCount
	}
	return 0
}

func (x *CacheItem) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_value_proto protoreflect.FileDescriptor

const file_value_proto_rawDesc = "" +
	"\n" +
	"\vvalue.proto\x12\x05proto\"\x7f\n" +
	"\tCacheItem\x12\x1c\n" +
	"\tcreatedAt\x18\x01 \x01(\x03R\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\x02 \x01(\x03R\tupdatedAt\x12\"\n" +
	"\fupdatedCount\x18\x03 \x01(\x03R\fupdatedCount\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04dataB\bZ\x06/protob\x06proto3"

var (
	file_value_proto_rawDescOnce sync.Once
	file_value_proto_rawDescData []byte
)

func file_value_proto_rawDescGZIP() []byte {
	file_value_proto_rawDescOnce.Do(func() {
		file_value_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_value_proto_rawDesc), len(file_value_proto_rawDesc)))
	})
	return file_value_proto_rawDescData
}

var file_value_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_value_proto_goTypes = []any{
	(*CacheItem)(nil), // 0: proto.CacheItem
}
var file_value_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_value_proto_init() }
func file_value_proto_init() {
	if File_value_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_value_proto_rawDesc), len(file_value_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_value_proto_goTypes,
		DependencyIndexes: file_value_proto_depIdxs,
		MessageInfos:      file_value_proto_msgTypes,
	}.Build()
	File_value_proto = out.File
	file_value_proto_goTypes = nil
	file_value_proto_depIdxs = nil
}
